AllCops:
  NewCops: enable
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "**/*_spec.rb"
Style/Documentation:
  Enabled: false
Naming/FileName:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/AbcSize:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
